//ACTION TYPES FOR RESTAURANT

//perform by restaurant owners
export const CREATE_RESTAURANT_REQUEST = "CREATE_RESTAURANT_REQUEST";
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS";
export const CREATE_RESTAURANT_FAILURE = "CREATE_RESTAURANT_FAILURE";

export const DELETE_RESTAURANT_REQUEST = "DELETE_RESTAURANT_REQUEST";
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS";
export const DELETE_RESTAURANT_FAILURE = "DELETE_RESTAURANT_FAILURE";

export const UPDATE_RESTAURANT_REQUEST = "UPDATE_RESTAURANT_REQUEST";
export const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS";
export const UPDATE_RESTAURANT_FAILURE = "UPDATE_RESTAURANT_FAILURE";

export const UPDATE_RESTAURANT_STATUS_REQUEST = "UPDATE_RESTAURANT_STATUS_REQUEST";
export const UPDATE_RESTAURANT_STATUS_SUCCESS = "UPDATE_RESTAURANT_STATUS_SUCCESS";
export const UPDATE_RESTAURANT_STATUS_FAILURE = "UPDATE_RESTAURANT_STATUS_FAILURE";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const GET_RESTAURANT_CATEGORY_REQUEST = "GET_RESTAURANT_CATEGORY_REQUEST";
export const GET_RESTAURANT_CATEGORY_SUCCESS = "GET_RESTAURANT_CATEGORY_SUCCESS";
export const GET_RESTAURANT_CATEGORY_FAILURE = "GET_RESTAURANT_CATEGORY_FAILURE";


//perform by customers
export const GET_ALL_RESTAURANTS_REQUEST = "GET_ALL_RESTAURANTS_REQUEST";
export const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS";
export const GET_ALL_RESTAURANTS_FAILURE = "GET_ALL_RESTAURANTS_FAILURE";

export const SEARCH_RESTAURANTS_BY_NAME_REQUEST = "SEARCH_RESTAURANTS_BY_NAME_REQUEST";
export const SEARCH_RESTAURANTS_BY_NAME_SUCCESS = "SEARCH_RESTAURANTS_BY_NAME_SUCCESS";
export const SEARCH_RESTAURANTS_BY_NAME_FAILURE = "SEARCH_RESTAURANTS_BY_NAME_FAILURE";

export const GET_RESTAURANTS_BY_ID_SUCCESS = "GET_RESTAURANTS_BY_ID_SUCCESS";
export const GET_RESTAURANTS_BY_ID_REQUEST = "GET_RESTAURANTS_BY_ID_REQUEST";
export const GET_RESTAURANTS_BY_ID_FAILURE = "GET_RESTAURANTS_BY_ID_FAILURE";

export const GET_RESTAURANTS_BY_USERID_SUCCESS = "GET_RESTAURANTS_BY_USERID_SUCCESS";
export const GET_RESTAURANTS_BY_USERID_REQUEST = "GET_RESTAURANTS_BY_USERID_REQUEST";
export const GET_RESTAURANTS_BY_USERID_FAILURE = "GET_RESTAURANTS_BY_USERID_FAILURE";




