
//user auth
export const REGISTER_REQUEST = "REGISTEER_REQUEST";
export const REGISTER_SUCCESS = "REGISTEER_SUCCESS";
export const REGISTER_FALIURE = "REGISTEER_FALIURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FALIURE = "LOGIN_FALIURE";

export const GET_USER_REQUEST="GET_USER_REQUEST";
export const GET_USER_FALIURE="GET_USER_FALIURE";
export const GET_USER_SUCCESS="GET_USER_SUCCESS";



export const LOGOUT="LOGOUT";

//user's favourites
export const ADD_TO_FAVOURITE_SUCCESS = "ADD_TO_FAVOURITE_SUCCESS";
export const ADD_TO_FAVOURITE_REQUEST = "ADD_TO_FAVOURITE_REQUEST";
export const ADD_TO_FAVOURITE_FALIURE = "ADD_TO_FAVOURITE_FALIURE";

